import java.math.BigInteger;
import java.util.Scanner;

// 9: Checking if a Number is a Lychrel Number.
// Difficulty: Hard  
// Topics: Number Theory, Reverse and Add Process  
/* Hint: A Lychrel number is a natural number that never forms a palindrome through the "reverse and add" process. 
   Keep reversing and adding until you reach a palindrome or a predefined iteration limit.
*/

// Example 1:
//      Input: `n = 56`  
//      Output: `Not a Lychrel Number`  
//      Explanation:
//          56 + 65 = 121 (Palindrome in 1 step)

// Example 2:
//      Input: `n = 196`  
//      Output: `Lychrel Number (Suspected)`  
//      Explanation:
//          196 + 691 = 887  
//          887 + 788 = 1675  
//          1675 + 5761 = 7436  
//          ... (Millions of iterations but no palindrome)  

public class LychrelNumberChecker {
    public static boolean isPalindrome(String str) {
        return str.equals(new StringBuilder(str).reverse().toString());
    }

    public static BigInteger reverseNumber(BigInteger num) {
        String reversedStr = new StringBuilder(num.toString(0)).reverse().toString();
        return new BigInteger(reversedStr);
    }

    public static boolean isLychrel(int num) {
        BigInteger number = BigInteger.valueOf(num);
        int maxIterations = 59; // Limit to prevent infinite loops
        for (int i = 0; i < maxIterations; i++) {
            number = number.add(reverseNumber(number));
            if (isPalindrome(number.toString())) {
                return false; // It's NOT a Lychrel number (formed a palindrome)
            }
        }
        return true;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter a number: ");
        int num = sc.nextInt();
        if (isLychrel(num)) {
            System.out.println(num + " is a Lychrel number.");
        } else {
            System.out.println(num + " is NOT a Lychrel number.");
        }
        sc.close();
    }
}

/*
 * ### **Why is 196 a Lychrel Number?**
 * The number **196** is the smallest number suspected to be a **Lychrel
 * number** because no known sequence of "reverse and add" operations has ever
 * resulted in a palindrome.
 * 
 * Unlike most numbers that eventually form a palindrome, **196 has been tested
 * for millions of iterations** without producing a palindrome. Because there is
 * no mathematical proof that it will never form one, it remains an **unproven**
 * but highly likely Lychrel number.
 * 
 * ---
 * 
 * ### **Understanding the Process**
 * A **Lychrel number** is a number that **never forms a palindrome** through
 * repeated "reverse and add" steps.
 * 
 * #### **Step-by-step Calculation for 196**
 * 1. **Reverse 196 and add**:
 * \[
 * 196 + 691 = 887
 * \]
 * 2. **Reverse 887 and add**:
 * \[
 * 887 + 788 = 1675
 * \]
 * 3. **Reverse 1675 and add**:
 * \[
 * 1675 + 5761 = 7436
 * \]
 * 4. **Reverse 7436 and add**:
 * \[
 * 7436 + 6347 = 13783
 * \]
 * 5. **Reverse 13783 and add**:
 * \[
 * 13783 + 38731 = 52514
 * \]
 * 6. **Repeat this process...**
 * - Even after **millions of iterations**, a palindrome has **never been
 * found**.
 * 
 * Thus, **196 is suspected to be a Lychrel number**.
 * 
 * ---
 * 
 * ### **Comparison with Non-Lychrel Numbers**
 * For example:
 * - **56** → 56 + 65 = **121** (Palindrome in 1 step)
 * - **89** → 89 + 98 = 187 → 187 + 781 = 968 → 968 + 869 = **1837** → … →
 * **8813200023188** (Palindrome in 24 steps)
 * - **196** → No palindrome even after millions of iterations.
 * 
 * ---
 * 
 * ### **Key Facts About 196 and Lychrel Numbers**
 * 1. **Unsolved Problem**: Mathematicians have not been able to prove whether
 * 196 will ever form a palindrome.
 * 2. **Large Numbers**: The numbers generated by the **196 process grow
 * exponentially**.
 * 3. **Not Proven, But Highly Likely**: Most researchers believe **196 is a
 * Lychrel number**, but a mathematical proof does not exist yet.
 * 
 */

// *_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*

/*
 * ### **Applications of Lychrel Numbers**
 * 
 * Lychrel numbers are primarily studied in mathematics and computer science due
 * to their unique properties and unsolved nature. Here are some applications
 * and significance of Lychrel numbers:
 * 
 * ### **1. Cryptography & Hash Functions**
 * - The unpredictable nature of Lychrel numbers makes them an interesting topic
 * in cryptography, particularly in designing secure hash functions and
 * pseudorandom number generators.
 * - Their iterative non-palindromic behavior can be used in encryption and
 * security algorithms.
 * 
 * ### **2. Number Theory & Mathematical Research**
 * - Lychrel numbers are a subject of ongoing research in **recreational
 * mathematics** and number theory.
 * - They are connected to problems in **integer sequences**, prime numbers, and
 * palindromes.
 * 
 * ### **3. Computer Science & Algorithm Testing**
 * - Detecting Lychrel numbers requires iterative computations, making them
 * useful for **algorithm testing** and **performance benchmarking**.
 * - Researchers use Lychrel number calculations to test the efficiency of
 * high-performance computing systems.
 * 
 * ### **4. Artificial Intelligence & Machine Learning**
 * - AI and ML models can study Lychrel numbers to analyze their patterns and
 * predict whether a given number will turn into a palindrome or remain a
 * Lychrel number.
 * 
 * ### **5. Chaos Theory & Complexity Analysis**
 * - Lychrel numbers exhibit chaotic behavior, making them an interesting
 * subject in **chaos theory** and **complexity analysis**.
 * - They can be used in modeling systems where outcomes are unpredictable.
 * 
 * ### **6. Recreational Mathematics & Puzzles**
 * - Lychrel numbers are used in math puzzles and competitions, challenging
 * mathematicians and enthusiasts to find new insights into their behavior.
 * 
 * ### **7. Data Science & Pattern Recognition**
 * - The study of Lychrel numbers can help in **pattern recognition**
 * techniques, especially in sequence analysis and data clustering.
 * 
 * Since **no one has yet proven whether 196 is truly a Lychrel number**, the
 * concept remains an open problem in mathematics, making it a fascinating area
 * of study. 🚀
 */